---

dictionaryDefinitions:
  - name: Spellcheck Overrides
    path: ./cspell_dictionary.txt
    addWords: true

dictionaries:
  - overrides

words:
  - blockstorage
  - CDPATH
  - checkwinsize
  - COLORTERM
  - Colour
  - concat
  - Containerfile
  - ensurepip
  - floatingip
  - gecos
  - gruntfuggly
  - histappend
  - HISTCONTROL
  - HISTFILESIZE
  - HISTSIZE
  - HISTTIMEFORMAT
  - ignoredups
  - ignorespace
  - iputils
  - keypair
  - nodocs
  - procps
  - recordset
  - regexall
  - secgroup
  - setopt
  - shopt
  - snapp
  - terrascan
  - tflint
  - tfsec
  - tfupdate
  - tfvars
  - toset
  - truecolor
  - userns

ignorePaths:
  - "**/.github/CODEOWNERS"
  - "**/.github/settings.yml"
  - "**/.gitignore"
  - "**/.pre-commit-config.yaml"
  - "**/cspell.config.yml"
